/**
 * Integration test: validates the built eslint-rules.json output
 * (generated by npm run build:rules). Ensures the data contract
 * expected by the app is respected.
 */
import fs from "fs";
import path from "path";

const BUILT_FILE = path.join(
  process.cwd(),
  "src",
  "data",
  "eslint-rules.json",
);

const REQUIRED_RULE_KEYS = [
  "id",
  "package",
  "url",
  "description",
  "deprecated",
  "type",
  "fixable",
  "hasSuggestions",
  "category",
] as const;

describe("Build output integration", () => {
  it("has a built eslint-rules.json file", () => {
    expect(fs.existsSync(BUILT_FILE)).toBe(true);
  });

  it("contains a valid rules array or legacy array format", () => {
    const raw = fs.readFileSync(BUILT_FILE, "utf8");
    const data = JSON.parse(raw);

    const rules = Array.isArray(data) ? data : data.rules;
    expect(rules).toBeDefined();
    expect(Array.isArray(rules)).toBe(true);
    expect(rules.length).toBeGreaterThan(0);
  });

  it("each rule has required fields", () => {
    const raw = fs.readFileSync(BUILT_FILE, "utf8");
    const data = JSON.parse(raw);
    const rules = Array.isArray(data) ? data : data.rules;

    for (const rule of rules.slice(0, 50)) {
      for (const key of REQUIRED_RULE_KEYS) {
        expect(rule).toHaveProperty(key);
      }
      expect(typeof rule.id).toBe("string");
      expect(typeof rule.package).toBe("string");
      expect(rule.id.length).toBeGreaterThan(0);
      expect(rule.package.length).toBeGreaterThan(0);
    }
  });

  it("pluginCount is a number when present (new format)", () => {
    const raw = fs.readFileSync(BUILT_FILE, "utf8");
    const data = JSON.parse(raw);
    if (!Array.isArray(data) && "pluginCount" in data) {
      expect(typeof data.pluginCount).toBe("number");
      expect(data.pluginCount).toBeGreaterThan(0);
    }
  });
});
